apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::600627356570:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-QI27ckMLUZZY
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::444455556666:user/pk
      username: pk
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 5d70b3ea-a84d-497a-aed6-070da2ef5e03
